query AllLocations($first: IntType = 500, $skip: IntType = 0) {
	allLocations(first: $first, skip: $skip, orderBy: [title_ASC], fallbackLocales: [sv]) {
		...LocationFragmentLight
	}

	_allLocationsMeta {
		count
	}
}

query Location($slug: String!) {
	location(filter: { slug: { eq: $slug } }) {
		...LocationFragment
	}
}
