query AllPrograms($first: IntType = 100, $skip: IntType = 0) {
	allPrograms(orderBy: [startDate_ASC, startTime_ASC], first: $first, skip: $skip) {
		...ProgramFragmentLight
	}
	_allProgramsMeta {
		count
	}
	allProgramCategories(orderBy: title_ASC, first: 100) {
		...ProgramCategoryFragment
	}
	_allProgramCategoriesMeta {
		count
	}
}

query Program($slug: String!) {
	program(filter: { slug: { eq: $slug } }) {
		...ProgramFragment
	}
}

query AllProgramCategories {
	allProgramCategories(orderBy: title_DESC, first: 100) {
		...ProgramCategoryFragment
	}
}

fragment ProgramCategoryFragment on ProgramCategoryRecord {
	id
	title
	plural
	slug
}

fragment ProgramFragmentLight on ProgramRecord {
	__typename
	_modelApiKey
	id
	title
	startDate
	startTime
	endDate
	intro(markdown: false)
	time
	startDate
	endDate
	groupShow
	image {
		...ImageThumbnailFragment
	}
	slug
	programCategory {
		id
		title
		slug
	}
}

fragment ProgramFragment on ProgramRecord {
	__typename
	_modelApiKey
	id
	title
	startDate
	endDate
	startTime
	time
	groupShow
	address
	image {
		...ImageFragment
	}
	thumb: image {
		...ImageThumbnailFragment
	}
	intro(markdown: false)
	misc
	location {
		...LocationFragmentLight
	}
	partner {
		...PartnerFragmentLight
	}
	programCategory {
		id
		title
	}
	slug
	externalLink
	content {
		value
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				layout
				image {
					...ImageFragment
				}
			}
			... on ImageGalleryRecord {
				__typename
				id
				images {
					...ImageThumbnailFragment
				}
			}

			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on RecordInterface {
				__typename
				id
			}
		}
	}
}
